spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    password: HR
    url: jdbc:oracle:thin:@10.90.1.105:1521/DEV
    username: HR
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: one-to-one-with-cache    
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8762/eureka 
